version: '3'
services:
  nats:
    image: 'nats:linux'
    container_name: nats.local
    expose:
      - "4222"
    ports:
      - "4222:4222"
    networks:
     - net1
  # consul:
    # image: 'consul:latest'
    # ports:
      # - "8500:8500"
      # - "8600:8600"
    # environment:
      # CONSUL_BIND_INTERFACE: eth0
    # networks:
      # - net1
  staxx:
    image: makerdao/staxx:dev
    container_name: staxx.local
    depends_on:
      - nats
    expose:
      - "9100-9105"
    ports:
      # - "9100-9105:9100-9105"
      - "4000:4000"
    environment:
      NATS_URL: nats.local
      GRAYLOG_HOST: graylog.local
      DOCKER_DEV_MODE_ALLOWED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/tmp/chains:/opt/chains"
      - "/tmp/snapshots:/opt/snapshots"
      - "/tmp/stacks:/opt/stacks"
    networks:
     - net1
  ex_testchain:
    image: makerdao/ex_testchain:dev
    container_name: ex-testchain.local
    expose:
      - "8500-8600"
      - "9100-9105"
    ports:
      - "8500-8600:8500-8600"
      # - "9100-9105:9100-9105"
    # environment:
    #   FRONT_URL: localhost
    volumes:
      - "/tmp/chains:/opt/chains"
      - "/tmp/snapshots:/opt/snapshots"
    networks:
     - net1
  testchain-deployment:
    image: makerdao/testchain-deployment:dev
    container_name: testchain-deployment.local
    ports:
      - "5001:5001"
    environment:
      TCD_GATEWAY: host=staxx.local
      GITHUB_DEFAULT_CHECKOUT_TARGET: master
    volumes:
      - nix-db:/nix
    tmpfs:
      - /tmp
    depends_on:
      - nats
    networks:
     - net1
  testchain-dashboard:
    image: makerdao/testchain-dashboard
    container_name: testchain-dashboard.local
    expose:
      - "3000"
    ports:
      - "4001:3000"
    depends_on:
      - staxx
    environment:
      TESTCHAIN_SERVICE_URL: http://localhost
      TESTCHAIN_SERVICE_PORT: 4000
      TESTCHAIN_SERVICE_WS_URL: ws://localhost:4000/socket
    networks:
     - net1
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
        - ./metrics_config/prometheus.yml:/etc/prometheus/prometheus.yml
    # command:
        # - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
    networks:
      - net1
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./metrics_config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - net1
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
    networks:
     - net1
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    networks:
     - net1
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    container_name: graylog.local
    image: graylog/graylog:3.1
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
     - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge

volumes:
  nix-db:
